### ISSUE TITLE
Setting to toggle save prompt on closing the preview pane

### ISSUE THREAD

**Issue by danielbayley** [aki77/atom-source-preview#7]
Since the last update to Atom (1.4.0 I think), source-preview has been giving a save prompt every time a preview pane is closed, which it didn’t do before. It would be good to have an option in settings to toggle this behaviour (and maybe set it to off by default).

**Comment by aki77** [comment]
Than you for informing.  I will fix it by next week.

**Comment by aki77** [comment]
Please try the latest version.

72e89372da7bc1a2e13bed09501a9d62c5a98af1

**Comment by danielbayley** [comment]
Fixed. :sunglasses:
