### ISSUE TITLE
Can this package be made to support a promise for a transform?

### ISSUE THREAD

**Issue by gandm** [aki77/atom-source-preview#8]
I have a package https://atom.io/packages/language-babel and which supports babel v5 and v6 transpiles. I would like to use your subscriber method to publish & view the results of my transpile output.  However, I use a background task to do the tranpspile which is asynchronous, as this solves many issues with different versions/plugins associated with multiple projects. Is their any chance I could pass back a Promise from the transform method that I can resolve at a future time with the transformed code and map?

Thanks.

**Comment by aki77** [comment]
Please try the latest version.

**Comment by gandm** [comment]
@aki77 Just added a version that supports it. Thanks again for your help. https://github.com/gandm/language-babel/issues/124

**Comment by aki77** [comment]
:smiley:
